---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/demo/model/h1_ign/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf"
  gz_topic_name: "/model/h1_ign/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/h1_ign/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS  
- gz_topic_name: /model/h1_ign/odometry
  ros_topic_name: /h1/odometry
  gz_type_name: ignition.msgs.Odometry
  ros_type_name: nav_msgs/msg/Odometry
  direction: GZ_TO_ROS  
- ros_topic_name: "/h1/left_ankle_pitch_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_ankle_pitch_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_ankle_roll_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_ankle_roll_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_elbow_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_elbow_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_hip_pitch_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_hip_pitch_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_hip_roll_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_hip_roll_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_hip_yaw_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_hip_yaw_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_knee_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_knee_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_shoulder_pitch_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_shoulder_pitch_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_shoulder_roll_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_shoulder_roll_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_shoulder_yaw_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/left_shoulder_yaw_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
#- ros_topic_name: "/h1/left_wrist_pitch_joint/cmd_pos"
#  gz_topic_name: "/model/h1_ign/joint/left_wrist_pitch_joint/0/cmd_pos"
#  ros_type_name: "std_msgs/msg/Float64"
#  gz_type_name: "gz.msgs.Double"
#  direction: ROS_TO_GZ
#- ros_topic_name: "/h1/left_wrist_roll_joint/cmd_pos"
#  gz_topic_name: "/model/h1_ign/joint/left_wrist_roll_joint/0/cmd_pos"
#  ros_type_name: "std_msgs/msg/Float64"
#  gz_type_name: "gz.msgs.Double"
#  direction: ROS_TO_GZ
#- ros_topic_name: "/h1/left_wrist_yaw_joint/cmd_pos"
#  gz_topic_name: "/model/h1_ign/joint/left_wrist_yaw_joint/0/cmd_pos"
#  ros_type_name: "std_msgs/msg/Float64"
#  gz_type_name: "gz.msgs.Double"
#  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_ankle_pitch_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_ankle_pitch_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_ankle_roll_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_ankle_roll_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_elbow_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_elbow_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_hip_pitch_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_hip_pitch_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_hip_roll_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_hip_roll_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_hip_yaw_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_hip_yaw_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_knee_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_knee_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_shoulder_pitch_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_shoulder_pitch_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_shoulder_roll_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_shoulder_roll_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/right_shoulder_yaw_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/right_shoulder_yaw_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
#- ros_topic_name: "/h1/right_wrist_pitch_joint/cmd_pos"
#  gz_topic_name: "/model/h1_ign/joint/right_wrist_pitch_joint/0/cmd_pos"
#  ros_type_name: "std_msgs/msg/Float64"
#  gz_type_name: "gz.msgs.Double"
#  direction: ROS_TO_GZ
#- ros_topic_name: "/h1/right_wrist_roll_joint/cmd_pos"
#  gz_topic_name: "/model/h1_ign/joint/right_wrist_roll_joint/0/cmd_pos"
#  ros_type_name: "std_msgs/msg/Float64"
#  gz_type_name: "gz.msgs.Double"
#  direction: ROS_TO_GZ
#- ros_topic_name: "/h1/right_wrist_yaw_joint/cmd_pos"
#  gz_topic_name: "/model/h1_ign/joint/right_wrist_yaw_joint/0/cmd_pos"
#  ros_type_name: "std_msgs/msg/Float64"
#  gz_type_name: "gz.msgs.Double"
#  direction: ROS_TO_GZ
- ros_topic_name: "/h1/torso_joint/cmd_pos"
  gz_topic_name: "/model/h1_ign/joint/torso_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/h1/left_contact_points"
  gz_topic_name: "/world/demo/model/h1_ign/link/left_ankle_roll_link/sensor/contact_sensor_left/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS  
- ros_topic_name: "/h1/right_contact_points"
  gz_topic_name: "/world/demo/model/h1_ign/link/right_ankle_roll_link/sensor/contact_sensor_right/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS  
- ros_topic_name: "/h1/left_ankle_joint/force_torque"
  gz_topic_name: "/left_ankle_joint/force_torque"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
- ros_topic_name: "/h1/right_ankle_joint/force_torque"
  gz_topic_name: "/right_ankle_joint/force_torque"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/camera/image_raw"
  gz_topic_name: "/camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/camera/depth_image"
  gz_topic_name: "/camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS